// GENERATED CODE - DO NOT EDIT BY HAND.
// Regenerate with scripts/codegen/generate_ocpp_v21_protocol.py

package com.monta.ocpp.emulator.ocpp.v21.protocol.messages

import com.monta.library.ocpp.common.profile.Feature
import com.monta.library.ocpp.common.profile.OcppConfirmation
import com.monta.library.ocpp.common.profile.OcppRequest
import com.monta.ocpp.emulator.ocpp.v21.protocol.messages.common.Address
import com.monta.ocpp.emulator.ocpp.v21.protocol.messages.common.CustomData
import com.monta.ocpp.emulator.ocpp.v21.protocol.messages.common.PaymentStatusEnum
import java.time.ZonedDateTime

object NotifySettlementFeature : Feature {
    override val name: String = "NotifySettlement"
    override val requestType: Class<out OcppRequest> = NotifySettlementRequest::class.java
    override val confirmationType: Class<out OcppConfirmation> = NotifySettlementResponse::class.java
}

/** OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License */
data class NotifySettlementRequest(
    /** The payment reference received from the payment terminal and is used as the value for _idToken_. */
    val pspRef: String,
    val status: PaymentStatusEnum,
    /** The amount that was settled, or attempted to be settled (in case of failure). */
    val settlementAmount: Double,
    /** The time when the settlement was done. */
    val settlementTime: ZonedDateTime,
    /** The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction. */
    val transactionId: String? = null,
    /** Additional information from payment terminal/payment process. */
    val statusInfo: String? = null,
    val receiptId: String? = null,
    /** The receipt URL, to be used if the receipt is generated by the payment terminal or the CS. */
    val receiptUrl: String? = null,
    val vatCompany: Address? = null,
    /** VAT number for a company receipt. */
    val vatNumber: String? = null,
    val customData: CustomData? = null,
) : OcppRequest

/** OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License */
data class NotifySettlementResponse(
    /** The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver. */
    val receiptUrl: String? = null,
    /** The receipt id if the receipt is generated by CSMS. */
    val receiptId: String? = null,
    val customData: CustomData? = null,
) : OcppConfirmation
